defaults:
  - /input_transform: repeat_global_vars.yaml
  - /optimizer: adamw.yaml

_target_: climart.models.CNNs.CNN.CNN_Net

hidden_dims: [256, 256, 256]
net_normalization: null
activation_function: "Gelu"
dropout: 0.0
gap: True


downwelling_loss_contribution: 0.5
upwelling_loss_contribution: 0.5
heating_rate_loss_contribution: 0

monitor: ${val_metric}
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.98