_target_: climart.models.CNNs.CNN.CNN_Net

input_size: 784
hidden_dims: [512, 256, 256]
net_normalization: null
activation_function: "Gelu"
dropout: 0.0
gap: True

monitor: ${val_metric}
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.98

optim:
  _target_: torch.optim.Adam
  lr: 2e-4
  weight_decay: 1e-6
