_target_: climart.models.GraphNet.graph_network.GN_withReadout

defaults:
  - /input_transform: graphnet_level_nodes.yaml
  - /optimizer: adamw.yaml

hidden_dims: [128, 128, 128]
net_normalization: null
activation_function: "Gelu"
dropout: 0.0
residual: True

update_mlp_n_layers: 1
aggregator_funcs: "mean"
graph_pooling: "mean"
readout_which_output: "nodes"

downwelling_loss_contribution: 0.5
upwelling_loss_contribution: 0.5
heating_rate_loss_contribution: 0

monitor: ${val_metric}
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.98
