_target_: climart.models.GraphNet.graph_network.GN_withReadout

hidden_dims: [128, 128, 128]
net_normalization: null
activation_function: "Gelu"
dropout: 0.0
residual: True

input_transform:
  _target_: climart.data_transform.transforms.LayerEdgesAndLevelNodesGraph
  exp_type: ${datamodule.exp_type}

update_mlp_n_layers: 1
aggregator_funcs: "mean"
graph_pooling: "mean"
readout_which_output: "nodes"

monitor: ${val_metric}
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.98
optim:
  _target_: torch.optim.Adam
  lr: 2e-4
  weight_decay: 1e-6
