defaults:
  - default.yaml

watch_model:
  _target_: climart.utils.wandb_callbacks.WatchModel
  log: "all"
  log_freq: 100

summarize_best_val_metric:
  _target_: climart.utils.wandb_callbacks.SummarizeBestValMetric

upload_best_ckpt_as_file:
  _target_: climart.utils.wandb_callbacks.UploadBestCheckpointAsFile
